/**
 * Scratchpad-only — not part of the app. Appends the in-page frame sampler (`frameSampler.mts`) to
 * the *built* `dist/index.html`, so the Android TV companion's WebView runs it on its next load.
 *
 * Injecting into the build output rather than into `src/` is deliberate: `dist/` is regenerated by
 * every `npm run build`, so the instrumentation can never survive into a real build by accident, and
 * nothing measurement-only ever lands in the app's own source.
 *
 * Usage: npx tsx QA/scratchpad/qa/tv-inject-sampler.mts <collector-origin>
 *   e.g. npx tsx QA/scratchpad/qa/tv-inject-sampler.mts http://192.168.0.213:4999
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { frameSamplerSource } from './frameSampler.mts'
import { capabilityProbeSource } from './capabilityProbe.mts'

const MARKER = '<!-- qa-frame-sampler -->'
const INDEX = 'dist/index.html'

const collector = process.argv[2]
if (!collector) throw new Error('usage: tv-inject-sampler.mts <collector-origin>')

const html = readFileSync(INDEX, 'utf-8')
if (html.includes(MARKER)) {
  console.log('[inject] already injected — rebuild first to start clean')
  process.exit(0)
}
// The capability probe (`capabilityProbe.mts`) rides along with the sampler rather than being
// injected separately: it needs the exact same one-line-into-`dist` delivery, fires once per load,
// and its answer (this WebView's Chromium version) is needed to interpret whatever the sampler in
// the same page then reports.
const script =
  `${MARKER}\n` +
  `<script>${capabilityProbeSource(`${collector}/capability`)}</script>\n` +
  `<script>${frameSamplerSource(`${collector}/frame`)}</script>\n`
writeFileSync(INDEX, html.replace('</body>', `${script}</body>`))
console.log(`[inject] sampler + capability probe injected into ${INDEX}, posting to ${collector}/frame and ${collector}/capability`)
