// Expo config plugin: the Tier 2/3 silent/prompted APK install flow (Update
// Channel spec §3.3/§4) — a custom native module (`PackageInstallerModule`,
// exposed to JS as `NativeModules.PackageInstallerModule`) that downloads
// the hub's current APK, verifies its signing certificate against this
// app's own embedded expectation, and commits it via Android's
// `PackageInstaller` session API. There's no Expo/RN wrapper for this
// (silent/device-owner installs are far too niche for a general-purpose
// package to cover), so this is genuinely new native surface area — kept
// to one focused module, registered the same way any hand-written RN
// native module would be (a `ReactPackage`, added to `MainApplication`'s
// own `getPackages()`).
//
// Only affects the Android prebuild; written fresh into android/ on every
// prebuild, not checked in. Written in plain CommonJS, same reason as
// every other plugin in this directory.
const { withAndroidManifest, withDangerousMod, withMainApplication } = require('expo/config-plugins')
const fs = require('fs')
const path = require('path')

const PACKAGE = 'no.adhdisplay.companion'

// SHA-256 fingerprint of keystore/release.keystore's own "adhdisplay" certificate (see that
// file's own keystore/KEYSTORE.md) — a downloaded-but-not-yet-installed APK's own signing
// certificate must match this before PackageInstallerModule will install it (Update Channel spec
// §3.3.2: the download itself is untrusted, plain HTTP on a shared LAN). Regenerate via:
//   keytool -list -v -keystore keystore/release.keystore -alias adhdisplay -storepass <password>
// then take the "SHA256:" line, strip the colons, lowercase it. Only needs regenerating if the
// release keystore itself is ever rotated — see KEYSTORE.md for why that's meant to never happen.
const EXPECTED_CERT_SHA256 = 'b18d5d31b6ae14d652c908fd4cd1fdb82c5453d447aa6efbde24b0e4492c3362'

const PACKAGE_INSTALLER_MODULE_SOURCE = `package ${PACKAGE}

import android.app.PendingIntent
import android.app.admin.DevicePolicyManager
import android.content.Context
import android.content.Intent
import android.content.pm.PackageInstaller
import android.content.pm.PackageManager
import android.os.Build
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.net.URL
import java.security.MessageDigest

/**
 * Generated by withPackageInstaller.js on every \`expo prebuild\` — do not
 * edit directly, edit that plugin instead. See this app's own Update
 * Channel spec §3.3 for the flow this implements: download to internal
 * storage, verify the signing certificate against EXPECTED_CERT_SHA256
 * (below), then commit via PackageInstaller. Exposed to JS as
 * NativeModules.PackageInstallerModule — see
 * adhdisplay-companion/src/lib/packageInstaller.ts for the JS-side wrapper.
 */
class PackageInstallerModule(private val reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(reactContext) {
  override fun getName() = "PackageInstallerModule"

  /** Whether this app currently has device-owner status (Update Channel spec Tier 2, §3.1). */
  @ReactMethod
  fun isDeviceOwner(promise: Promise) {
    try {
      val dpm = reactContext.getSystemService(Context.DEVICE_POLICY_SERVICE) as DevicePolicyManager
      promise.resolve(dpm.isDeviceOwnerApp(reactContext.packageName))
    } catch (e: Exception) {
      promise.reject("DEVICE_OWNER_CHECK_FAILED", e.message, e)
    }
  }

  /** Whether this app currently has the one-time "install unknown apps" grant (Tier 3, §4). Devices below API 26 have no such per-app gate (a single global Settings toggle covers it instead), so this resolves true unconditionally there. */
  @ReactMethod
  fun canRequestPackageInstalls(promise: Promise) {
    try {
      val canInstall = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
        reactContext.packageManager.canRequestPackageInstalls()
      } else {
        true
      }
      promise.resolve(canInstall)
    } catch (e: Exception) {
      promise.reject("INSTALL_PERMISSION_CHECK_FAILED", e.message, e)
    }
  }

  /**
   * Downloads \`url\` to internal storage, verifies its signing certificate
   * matches EXPECTED_CERT_SHA256, then commits it via a PackageInstaller
   * session — on a device-owner unit this installs silently with no
   * dialog; otherwise Android shows its own confirmation UI automatically
   * (Tier 3), same code path either way, the OS decides which based on
   * this app's own privilege level, not this function.
   *
   * Runs on a background thread — network + file I/O would otherwise block
   * the JS bridge thread. Per spec §3.3.4, this process is expected to be
   * killed mid-install once the commit's own PendingIntent fires — this
   * promise resolving is NOT a success signal and callers must not treat
   * it as one; the only real confirmation is the next heartbeat's own
   * versionCode (see server/index.ts).
   */
  @ReactMethod
  fun downloadVerifyAndInstall(url: String, promise: Promise) {
    Thread {
      val file = File(reactContext.filesDir, "pending-update.apk")
      try {
        URL(url).openStream().use { input ->
          FileOutputStream(file).use { output -> input.copyTo(output) }
        }

        if (!verifyCertificate(file)) {
          file.delete()
          promise.reject("SIGNATURE_MISMATCH", "Downloaded APK's signing certificate does not match this app's own embedded expectation")
          return@Thread
        }

        val packageInstaller = reactContext.packageManager.packageInstaller
        val params = PackageInstaller.SessionParams(PackageInstaller.SessionParams.MODE_FULL_INSTALL)
        val sessionId = packageInstaller.createSession(params)
        val session = packageInstaller.openSession(sessionId)
        session.openWrite("update", 0, file.length()).use { out ->
          FileInputStream(file).use { it.copyTo(out) }
          session.fsync(out)
        }

        val intent = Intent(reactContext, PackageInstallReceiver::class.java)
        val flags = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) PendingIntent.FLAG_MUTABLE else 0
        val pendingIntent = PendingIntent.getBroadcast(reactContext, sessionId, intent, flags)
        session.commit(pendingIntent.intentSender)
        session.close()
        promise.resolve(true)
      } catch (e: Exception) {
        promise.reject("INSTALL_FAILED", e.message, e)
      }
    }.start()
  }

  private fun verifyCertificate(file: File): Boolean {
    val flags = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) PackageManager.GET_SIGNING_CERTIFICATES else PackageManager.GET_SIGNATURES
    val info = reactContext.packageManager.getPackageArchiveInfo(file.absolutePath, flags) ?: return false
    val signatures = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
      info.signingInfo?.apkContentsSigners
    } else {
      @Suppress("DEPRECATION")
      info.signatures
    }
    if (signatures.isNullOrEmpty()) return false
    val digest = MessageDigest.getInstance("SHA-256")
    return signatures.any { signature ->
      val fingerprint = digest.digest(signature.toByteArray()).joinToString("") { "%02x".format(it) }
      fingerprint.equals("${EXPECTED_CERT_SHA256}", ignoreCase = true)
    }
  }
}
`

const PACKAGE_INSTALLER_PACKAGE_SOURCE = `package ${PACKAGE}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/** Registers PackageInstallerModule.kt — see this file's own doc comment. Generated by withPackageInstaller.js. */
class PackageInstallerPackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> {
    return listOf(PackageInstallerModule(reactContext))
  }

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> {
    return emptyList()
  }
}
`

const PACKAGE_INSTALL_RECEIVER_SOURCE = `package ${PACKAGE}

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.pm.PackageInstaller
import android.util.Log

/**
 * Target of the PendingIntent PackageInstallerModule.downloadVerifyAndInstall's own
 * session.commit() call requires — Android's PackageInstaller API mandates a commit target even
 * though this app deliberately doesn't rely on it firing (Update Channel spec §3.3.4: the process
 * is expected to be killed mid-install, and the only real confirmation of success is the next
 * heartbeat's own versionCode, not this receiver). Only logs, for whatever diagnostic value
 * survives in logcat if the process happens to still be alive when this fires (e.g. a Tier 3
 * install where the user just tapped "Install" and the app wasn't killed).
 */
class PackageInstallReceiver : BroadcastReceiver() {
  override fun onReceive(context: Context, intent: Intent) {
    val status = intent.getIntExtra(PackageInstaller.EXTRA_STATUS, PackageInstaller.STATUS_FAILURE)
    val message = intent.getStringExtra(PackageInstaller.EXTRA_STATUS_MESSAGE)
    Log.i("PackageInstallReceiver", "Install session result: status=$status message=$message")
  }
}
`

function withPackageInstallerManifest(config) {
  return withAndroidManifest(config, (config) => {
    const manifest = config.modResults
    const application = manifest.manifest.application?.[0]
    if (!application) return config

    manifest.manifest['uses-permission'] = manifest.manifest['uses-permission'] ?? []
    const hasPermission = manifest.manifest['uses-permission'].some(
      (entry) => entry.$?.['android:name'] === 'android.permission.REQUEST_INSTALL_PACKAGES',
    )
    if (!hasPermission) {
      manifest.manifest['uses-permission'].push({ $: { 'android:name': 'android.permission.REQUEST_INSTALL_PACKAGES' } })
    }

    application.receiver = application.receiver ?? []
    const hasReceiver = application.receiver.some((entry) => entry.$?.['android:name'] === '.PackageInstallReceiver')
    if (!hasReceiver) {
      application.receiver.push({ $: { 'android:name': '.PackageInstallReceiver', 'android:exported': 'false' } })
    }
    return config
  })
}

function withPackageInstallerSource(config) {
  return withDangerousMod(config, [
    'android',
    (config) => {
      const packagePath = PACKAGE.split('.').join(path.sep)
      const javaDir = path.join(config.modRequest.platformProjectRoot, 'app', 'src', 'main', 'java', packagePath)
      fs.mkdirSync(javaDir, { recursive: true })
      fs.writeFileSync(path.join(javaDir, 'PackageInstallerModule.kt'), PACKAGE_INSTALLER_MODULE_SOURCE, 'utf-8')
      fs.writeFileSync(path.join(javaDir, 'PackageInstallerPackage.kt'), PACKAGE_INSTALLER_PACKAGE_SOURCE, 'utf-8')
      fs.writeFileSync(path.join(javaDir, 'PackageInstallReceiver.kt'), PACKAGE_INSTALL_RECEIVER_SOURCE, 'utf-8')
      return config
    },
  ])
}

// The exact line RN/Expo's own MainApplication template generates inside getPackages() — see
// that file's own generated shape. Targeted narrowly (not just "does PackageInstallerPackage
// appear anywhere") so re-running prebuild is idempotent rather than appending a second
// packages.add(...) call every time.
const PACKAGES_VAL_LINE = 'val packages = PackageList(this).packages'

function withPackageInstallerRegistration(config) {
  return withMainApplication(config, (config) => {
    if (config.modResults.language !== 'kt') {
      throw new Error('withPackageInstaller: expected a Kotlin android/app/.../MainApplication.kt')
    }
    let contents = config.modResults.contents

    if (!contents.includes(PACKAGES_VAL_LINE)) {
      throw new Error(
        'withPackageInstaller: could not find the expected "val packages = PackageList(this).packages" line in ' +
          'MainApplication.kt to register PackageInstallerPackage against — the RN/Expo template may have changed.',
      )
    }
    if (!contents.includes('packages.add(PackageInstallerPackage())')) {
      contents = contents.replace(PACKAGES_VAL_LINE, `${PACKAGES_VAL_LINE}\n            packages.add(PackageInstallerPackage())`)
    }

    config.modResults.contents = contents
    return config
  })
}

module.exports = function withPackageInstaller(config) {
  config = withPackageInstallerManifest(config)
  config = withPackageInstallerSource(config)
  config = withPackageInstallerRegistration(config)
  return config
}
