// Expo config plugin: printing receipts on a USB printer plugged straight into the tablet — a custom
// native module (`UsbPrinterModule`, exposed to JS as `NativeModules.UsbPrinterModule`) that lists
// attached receipt printers and sends them raw ESC/POS bytes over Android's USB host API. The kiosk
// page builds the receipt itself (the main app's shared `src/lib/receipt`) and asks for it to be sent
// through the WebView bridge (`src/lib/webViewBridge.ts`); this module only moves bytes.
//
// There's no maintained RN/Expo package for raw USB bulk transfer that fits this app's plain-Kotlin,
// generate-on-prebuild posture, so it's written the same way as `withPackageInstaller.js`: Kotlin
// source written into android/ on every prebuild, registered as a `ReactPackage` in
// `MainApplication`. Written in plain CommonJS, same reason as every other plugin in this directory.
const { withAndroidManifest, withDangerousMod, withMainApplication } = require('expo/config-plugins')
const fs = require('fs')
const path = require('path')

const PACKAGE = 'no.adhdisplay.companion'

const USB_PRINTER_MODULE_SOURCE = `package ${PACKAGE}

import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.hardware.usb.UsbConstants
import android.hardware.usb.UsbDevice
import android.hardware.usb.UsbEndpoint
import android.hardware.usb.UsbInterface
import android.hardware.usb.UsbManager
import android.os.Build
import android.util.Base64
import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

/**
 * Generated by withUsbPrinter.js on every \`expo prebuild\` — do not edit directly, edit that plugin
 * instead. Receipt printers plugged into this device by USB: \`listPrinters\` finds them, \`print\` sends
 * one a finished ESC/POS job. Exposed to JS as NativeModules.UsbPrinterModule — see
 * adhdisplay-companion/src/lib/usbPrinter.ts for the JS-side wrapper.
 *
 * A device counts as a receipt printer if it has a USB printer-class interface (class 7) with a bulk
 * OUT endpoint — or, since many receipt printers present a vendor-specific interface instead, if it
 * comes from a known receipt-printer vendor and has any interface with a bulk OUT endpoint.
 */
class UsbPrinterModule(private val reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(reactContext) {
  override fun getName() = "UsbPrinterModule"

  private val usbManager: UsbManager
    get() = reactContext.getSystemService(Context.USB_SERVICE) as UsbManager

  /** Vendor ids of receipt-printer makers whose printers often use a vendor-specific USB interface: Epson, Star, Bixolon, SNBC, Custom, Citizen, and the ids common on unbranded/Xprinter-style printers. */
  private val receiptVendors = setOf(0x04b8, 0x0519, 0x1504, 0x154f, 0x0dd4, 0x1d90, 0x0483, 0x0416, 0x1fc9, 0x0fe6, 0x28e9, 0x6868, 0x20d1)

  private fun bulkOut(usbInterface: UsbInterface): UsbEndpoint? =
    (0 until usbInterface.endpointCount).map { usbInterface.getEndpoint(it) }.firstOrNull { it.type == UsbConstants.USB_ENDPOINT_XFER_BULK && it.direction == UsbConstants.USB_DIR_OUT }

  /** The interface + endpoint to send a job through, or null if this device isn't a receipt printer. */
  private fun printerChannel(device: UsbDevice): Pair<UsbInterface, UsbEndpoint>? {
    val interfaces = (0 until device.interfaceCount).map { device.getInterface(it) }
    interfaces.firstOrNull { it.interfaceClass == UsbConstants.USB_CLASS_PRINTER && bulkOut(it) != null }?.let { return it to bulkOut(it)!! }
    if (device.vendorId in receiptVendors) interfaces.firstOrNull { bulkOut(it) != null }?.let { return it to bulkOut(it)!! }
    return null
  }

  /** Stable across replugs and reboots — vendor and product id. (The serial number would tell two identical printers apart, but Android only reveals it after the user grants access.) */
  private fun keyOf(device: UsbDevice) = "%04x:%04x".format(device.vendorId, device.productId)

  private fun nameOf(device: UsbDevice): String {
    val product = try { device.productName } catch (e: SecurityException) { null }
    val maker = try { device.manufacturerName } catch (e: SecurityException) { null }
    return listOfNotNull(maker, product).joinToString(" ").ifBlank { "USB printer " + keyOf(device) }
  }

  private fun printers(): List<UsbDevice> = usbManager.deviceList.values.filter { printerChannel(it) != null }

  @ReactMethod
  fun listPrinters(promise: Promise) {
    try {
      val result = Arguments.createArray()
      for (device in printers()) {
        val entry = Arguments.createMap()
        entry.putString("key", keyOf(device))
        entry.putString("name", nameOf(device))
        result.pushMap(entry)
      }
      promise.resolve(result)
    } catch (e: Exception) {
      promise.reject("USB_LIST_FAILED", e.message, e)
    }
  }

  /** Sends \`base64\` (a whole ESC/POS job) to the printer with this key. Asks for USB access first if this app doesn't have it yet — Android then shows its own "Allow access?" dialog, once per printer. */
  @ReactMethod
  fun print(key: String, base64: String, promise: Promise) {
    val device = printers().firstOrNull { keyOf(it) == key }
    if (device == null) {
      promise.reject("USB_PRINTER_NOT_FOUND", "The USB printer is not connected")
      return
    }
    val bytes = try { Base64.decode(base64, Base64.DEFAULT) } catch (e: IllegalArgumentException) {
      promise.reject("USB_BAD_DATA", "Invalid print data", e)
      return
    }
    if (usbManager.hasPermission(device)) {
      send(device, bytes, promise)
      return
    }
    requestPermission(device) { granted ->
      if (granted) send(device, bytes, promise) else promise.reject("USB_PERMISSION_DENIED", "Access to the USB printer was not allowed")
    }
  }

  private fun requestPermission(device: UsbDevice, onResult: (Boolean) -> Unit) {
    val action = reactContext.packageName + ".USB_PRINTER_PERMISSION"
    val receiver = object : BroadcastReceiver() {
      override fun onReceive(context: Context, intent: Intent) {
        if (intent.action != action) return
        try { reactContext.unregisterReceiver(this) } catch (_: IllegalArgumentException) {}
        onResult(intent.getBooleanExtra(UsbManager.EXTRA_PERMISSION_GRANTED, false))
      }
    }
    val filter = IntentFilter(action)
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
      reactContext.registerReceiver(receiver, filter, Context.RECEIVER_NOT_EXPORTED)
    } else {
      @Suppress("UnspecifiedRegisterReceiverFlag")
      reactContext.registerReceiver(receiver, filter)
    }
    // Explicit (setPackage) and mutable: the system writes EXTRA_PERMISSION_GRANTED into it, and
    // Android 14+ rejects a mutable PendingIntent wrapping an implicit Intent.
    val intent = Intent(action).setPackage(reactContext.packageName)
    val flags = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) PendingIntent.FLAG_MUTABLE else 0
    usbManager.requestPermission(device, PendingIntent.getBroadcast(reactContext, 0, intent, flags))
  }

  /** Writes the job in bulk-transfer chunks on a background thread — USB I/O must never block the JS bridge. */
  private fun send(device: UsbDevice, bytes: ByteArray, promise: Promise) {
    Thread {
      val channel = printerChannel(device)
      val connection = usbManager.openDevice(device)
      if (channel == null || connection == null) {
        promise.reject("USB_OPEN_FAILED", "Could not open the USB printer")
        return@Thread
      }
      val (usbInterface, endpoint) = channel
      try {
        if (!connection.claimInterface(usbInterface, true)) {
          promise.reject("USB_CLAIM_FAILED", "The USB printer is in use")
          return@Thread
        }
        var offset = 0
        while (offset < bytes.size) {
          val length = minOf(CHUNK_SIZE, bytes.size - offset)
          val written = connection.bulkTransfer(endpoint, bytes, offset, length, TIMEOUT_MS)
          // 0 is a failure too: the printer took nothing, and retrying the same chunk forever would hang this thread.
          if (written <= 0) {
            promise.reject("USB_WRITE_FAILED", "The USB printer did not accept the data")
            return@Thread
          }
          offset += written
        }
        promise.resolve(null)
      } catch (e: Exception) {
        promise.reject("USB_WRITE_FAILED", e.message, e)
      } finally {
        connection.releaseInterface(usbInterface)
        connection.close()
      }
    }.start()
  }

  companion object {
    private const val CHUNK_SIZE = 4096
    private const val TIMEOUT_MS = 5000
  }
}
`

const USB_PRINTER_PACKAGE_SOURCE = `package ${PACKAGE}

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

/** Registers UsbPrinterModule.kt. Generated by withUsbPrinter.js. */
class UsbPrinterPackage : ReactPackage {
  override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> {
    return listOf(UsbPrinterModule(reactContext))
  }

  override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> {
    return emptyList()
  }
}
`

/** Declares USB host support as optional, so the app still installs on a device without it (every Android TV stick, for one). */
function withUsbHostFeature(config) {
  return withAndroidManifest(config, (config) => {
    const manifest = config.modResults.manifest
    manifest['uses-feature'] = manifest['uses-feature'] ?? []
    if (!manifest['uses-feature'].some((entry) => entry.$?.['android:name'] === 'android.hardware.usb.host')) {
      manifest['uses-feature'].push({ $: { 'android:name': 'android.hardware.usb.host', 'android:required': 'false' } })
    }
    return config
  })
}

function withUsbPrinterSource(config) {
  return withDangerousMod(config, [
    'android',
    (config) => {
      const javaDir = path.join(config.modRequest.platformProjectRoot, 'app', 'src', 'main', 'java', ...PACKAGE.split('.'))
      fs.mkdirSync(javaDir, { recursive: true })
      fs.writeFileSync(path.join(javaDir, 'UsbPrinterModule.kt'), USB_PRINTER_MODULE_SOURCE, 'utf-8')
      fs.writeFileSync(path.join(javaDir, 'UsbPrinterPackage.kt'), USB_PRINTER_PACKAGE_SOURCE, 'utf-8')
      return config
    },
  ])
}

const PACKAGES_VAL_LINE = 'val packages = PackageList(this).packages'

function withUsbPrinterRegistration(config) {
  return withMainApplication(config, (config) => {
    if (config.modResults.language !== 'kt') {
      throw new Error('withUsbPrinter: expected a Kotlin android/app/.../MainApplication.kt')
    }
    let contents = config.modResults.contents
    if (!contents.includes(PACKAGES_VAL_LINE)) {
      throw new Error('withUsbPrinter: could not find "val packages = PackageList(this).packages" in MainApplication.kt to register UsbPrinterPackage against.')
    }
    if (!contents.includes('packages.add(UsbPrinterPackage())')) {
      contents = contents.replace(PACKAGES_VAL_LINE, `${PACKAGES_VAL_LINE}\n            packages.add(UsbPrinterPackage())`)
    }
    config.modResults.contents = contents
    return config
  })
}

module.exports = function withUsbPrinter(config) {
  config = withUsbHostFeature(config)
  config = withUsbPrinterSource(config)
  config = withUsbPrinterRegistration(config)
  return config
}
