name: DeepSeek Config
version: 1.0.0
schema: v1

models:
  - name: DeepSeek V4 Flash
    provider: deepseek
    model: deepseek-v4-flash
    apiKey: sk-01884aacf18a419d934e33c625336987
    roles:
      - chat
      - edit
      - apply
    capabilities:
      - tool_use

  - name: DeepSeek V4 Pro
    provider: deepseek
    model: deepseek-v4-pro
    apiKey: sk-01884aacf18a419d934e33c625336987
    roles:
      - chat
      - edit
    capabilities:
      - tool_use

  - name: qwen2.5-coder 7b
    provider: ollama
    model: qwen2.5-coder:7b
    roles:
      - autocomplete

context:
  - provider: code
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase